ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

server:
  port: 17001